#!/usr/bin/env bash
# Submit every input_p*_bin*.ini generated by generate_bins.py as its own
# LSF job. Run this from MCFM-10.3/Bin, after generate_bins.py has run.
set -euo pipefail

for f in input_p*_bin*.ini; do
    [ -e "$f" ] || continue   # no matches -> skip instead of literal glob
    runstring=$(basename "$f" .ini | sed 's/^input_//')
    bsub -q l -n 2 -R "span[hosts=1]" -o "${runstring}.log" -e "${runstring}.err" \
      "ulimit -s unlimited; export OMP_NUM_THREADS=2; export OMP_STACKSIZE=512M; ./mcfm $f"
    echo "submitted ${runstring}"
done